v9: 218f0a6 Merge pull request #5507 from leofang/v9_cusparse_fix
============================= test session starts ==============================
platform linux -- Python 3.8.7, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/kmaeh/Development/cupy-rocm-ci-report/tools/tmp.SzviMCwxMF/cupy, configfile: setup.cfg
plugins: html-3.1.1, metadata-1.11.0
collected 61463 items / 7 errors / 67 deselected / 12 skipped / 61377 selected

==================================== ERRORS ====================================
__________ ERROR collecting tests/cupy_tests/core_tests/test_core.py ___________
tests/cupy_tests/core_tests/test_core.py:10: in <module>
    from cupy_tests.core_tests import test_raw
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
/home/kmaeh/.pyenv/versions/rocm-ci/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
tests/cupy_tests/core_tests/test_raw.py:1088: in <module>
    60 <= int(cupy.cuda.device.get_compute_capability()),
cupy/cuda/device.pyx:84: in cupy.cuda.device.get_compute_capability
    cpdef str get_compute_capability():
cupy/cuda/device.pyx:85: in cupy.cuda.device.get_compute_capability
    dev_id = get_device_id()
cupy/cuda/device.pyx:47: in cupy.cuda.device.get_device_id
    return runtime.getDevice()
cupy_backends/cuda/api/runtime.pyx:289: in cupy_backends.cuda.api.runtime.getDevice
    check_status(status)
cupy_backends/cuda/api/runtime.pyx:261: in cupy_backends.cuda.api.runtime.check_status
    raise CUDARuntimeError(status)
E   cupy_backends.cuda.api.runtime.CUDARuntimeError: hipErrorNoDevice: hipErrorNoDevice
___________ ERROR collecting tests/cupy_tests/core_tests/test_raw.py ___________
tests/cupy_tests/core_tests/test_raw.py:1088: in <module>
    60 <= int(cupy.cuda.device.get_compute_capability()),
cupy/cuda/device.pyx:84: in cupy.cuda.device.get_compute_capability
    cpdef str get_compute_capability():
cupy/cuda/device.pyx:85: in cupy.cuda.device.get_compute_capability
    dev_id = get_device_id()
cupy/cuda/device.pyx:47: in cupy.cuda.device.get_device_id
    return runtime.getDevice()
cupy_backends/cuda/api/runtime.pyx:289: in cupy_backends.cuda.api.runtime.getDevice
    check_status(status)
cupy_backends/cuda/api/runtime.pyx:261: in cupy_backends.cuda.api.runtime.check_status
    raise CUDARuntimeError(status)
E   cupy_backends.cuda.api.runtime.CUDARuntimeError: hipErrorNoDevice: hipErrorNoDevice
__________ ERROR collecting tests/cupy_tests/cuda_tests/test_cufft.py __________
tests/cupy_tests/cuda_tests/test_cufft.py:116: in <module>
    class TestXtPlanNd(unittest.TestCase):
tests/cupy_tests/cuda_tests/test_cufft.py:164: in TestXtPlanNd
    ???
cupy/cuda/device.pyx:84: in cupy.cuda.device.get_compute_capability
    cpdef str get_compute_capability():
cupy/cuda/device.pyx:85: in cupy.cuda.device.get_compute_capability
    dev_id = get_device_id()
cupy/cuda/device.pyx:47: in cupy.cuda.device.get_device_id
    return runtime.getDevice()
cupy_backends/cuda/api/runtime.pyx:289: in cupy_backends.cuda.api.runtime.getDevice
    check_status(status)
cupy_backends/cuda/api/runtime.pyx:261: in cupy_backends.cuda.api.runtime.check_status
    raise CUDARuntimeError(status)
E   cupy_backends.cuda.api.runtime.CUDARuntimeError: hipErrorNoDevice: hipErrorNoDevice
__________ ERROR collecting tests/cupy_tests/fft_tests/test_cache.py ___________
tests/cupy_tests/fft_tests/test_cache.py:26: in <module>
    n_devices = runtime.getDeviceCount()
cupy_backends/cuda/api/runtime.pyx:477: in cupy_backends.cuda.api.runtime.getDeviceCount
    cpdef int getDeviceCount() except? -1:
cupy_backends/cuda/api/runtime.pyx:480: in cupy_backends.cuda.api.runtime.getDeviceCount
    check_status(status)
cupy_backends/cuda/api/runtime.pyx:261: in cupy_backends.cuda.api.runtime.check_status
    raise CUDARuntimeError(status)
E   cupy_backends.cuda.api.runtime.CUDARuntimeError: hipErrorNoDevice: hipErrorNoDevice
_______ ERROR collecting tests/cupy_tests/indexing_tests/test_iterate.py _______
tests/cupy_tests/indexing_tests/test_iterate.py:124: in <module>
    ???
cupy/_creation/from_data.py:41: in array
    return _core.array(obj, dtype, copy, order, subok, ndmin)
cupy/_core/core.pyx:2167: in cupy._core.core.array
    cpdef ndarray array(obj, dtype=None, bint copy=True, order='K',
cupy/_core/core.pyx:2246: in cupy._core.core.array
    return _send_object_to_gpu(obj, dtype, order, ndmin)
cupy/_core/core.pyx:2320: in cupy._core.core._send_object_to_gpu
    cdef ndarray a = ndarray(a_shape, dtype=a_dtype, order=order)
cupy/_core/core.pyx:164: in cupy._core.core.ndarray.__init__
    self.data = memory.alloc(self.size * itemsize)
cupy/cuda/memory.pyx:718: in cupy.cuda.memory.alloc
    return get_allocator()(size)
cupy/cuda/memory.pyx:1395: in cupy.cuda.memory.MemoryPool.malloc
    cpdef MemoryPointer malloc(self, size_t size):
cupy/cuda/memory.pyx:1415: in cupy.cuda.memory.MemoryPool.malloc
    mp = <SingleDeviceMemoryPool>self._pools[device.get_device_id()]
cupy/cuda/device.pyx:47: in cupy.cuda.device.get_device_id
    return runtime.getDevice()
cupy_backends/cuda/api/runtime.pyx:289: in cupy_backends.cuda.api.runtime.getDevice
    check_status(status)
cupy_backends/cuda/api/runtime.pyx:261: in cupy_backends.cuda.api.runtime.check_status
    raise CUDARuntimeError(status)
E   cupy_backends.cuda.api.runtime.CUDARuntimeError: hipErrorNoDevice: hipErrorNoDevice
_______ ERROR collecting tests/cupy_tests/random_tests/test_generator.py _______
tests/cupy_tests/random_tests/test_generator.py:212: in <module>
    ???
cupy/_creation/from_data.py:41: in array
    return _core.array(obj, dtype, copy, order, subok, ndmin)
cupy/_core/core.pyx:2167: in cupy._core.core.array
    cpdef ndarray array(obj, dtype=None, bint copy=True, order='K',
cupy/_core/core.pyx:2246: in cupy._core.core.array
    return _send_object_to_gpu(obj, dtype, order, ndmin)
cupy/_core/core.pyx:2320: in cupy._core.core._send_object_to_gpu
    cdef ndarray a = ndarray(a_shape, dtype=a_dtype, order=order)
cupy/_core/core.pyx:164: in cupy._core.core.ndarray.__init__
    self.data = memory.alloc(self.size * itemsize)
cupy/cuda/memory.pyx:718: in cupy.cuda.memory.alloc
    return get_allocator()(size)
cupy/cuda/memory.pyx:1395: in cupy.cuda.memory.MemoryPool.malloc
    cpdef MemoryPointer malloc(self, size_t size):
cupy/cuda/memory.pyx:1415: in cupy.cuda.memory.MemoryPool.malloc
    mp = <SingleDeviceMemoryPool>self._pools[device.get_device_id()]
cupy/cuda/device.pyx:47: in cupy.cuda.device.get_device_id
    return runtime.getDevice()
cupy_backends/cuda/api/runtime.pyx:289: in cupy_backends.cuda.api.runtime.getDevice
    check_status(status)
cupy_backends/cuda/api/runtime.pyx:261: in cupy_backends.cuda.api.runtime.check_status
    raise CUDARuntimeError(status)
E   cupy_backends.cuda.api.runtime.CUDARuntimeError: hipErrorNoDevice: hipErrorNoDevice
_____ ERROR collecting tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py _____
tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py:1036: in <module>
    class TestRfft2(unittest.TestCase):
tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py:1147: in TestRfft2
    ???
cupy/cuda/device.pyx:84: in cupy.cuda.device.get_compute_capability
    cpdef str get_compute_capability():
cupy/cuda/device.pyx:85: in cupy.cuda.device.get_compute_capability
    dev_id = get_device_id()
cupy/cuda/device.pyx:47: in cupy.cuda.device.get_device_id
    return runtime.getDevice()
cupy_backends/cuda/api/runtime.pyx:289: in cupy_backends.cuda.api.runtime.getDevice
    check_status(status)
cupy_backends/cuda/api/runtime.pyx:261: in cupy_backends.cuda.api.runtime.check_status
    raise CUDARuntimeError(status)
E   cupy_backends.cuda.api.runtime.CUDARuntimeError: hipErrorNoDevice: hipErrorNoDevice
- generated html file: file:///home/kmaeh/Development/cupy-rocm-ci-report/tools/tmp.SzviMCwxMF/cupy/_output/report.html -
=========================== short test summary info ============================
ERROR tests/cupy_tests/core_tests/test_core.py - cupy_backends.cuda.api.runti...
ERROR tests/cupy_tests/core_tests/test_raw.py - cupy_backends.cuda.api.runtim...
ERROR tests/cupy_tests/cuda_tests/test_cufft.py - cupy_backends.cuda.api.runt...
ERROR tests/cupy_tests/fft_tests/test_cache.py - cupy_backends.cuda.api.runti...
ERROR tests/cupy_tests/indexing_tests/test_iterate.py - cupy_backends.cuda.ap...
ERROR tests/cupy_tests/random_tests/test_generator.py - cupy_backends.cuda.ap...
ERROR tests/cupyx_tests/scipy_tests/fft_tests/test_fft.py - cupy_backends.cud...
!!!!!!!!!!!!!!!!!!! Interrupted: 7 errors during collection !!!!!!!!!!!!!!!!!!!!
================ 12 skipped, 67 deselected, 7 errors in 23.62s =================
